import type { InventoryCategory, InventoryItem } from '../inventory/catalog';
import { QIPPO_FIGMA, qippoFigmaUrl } from './figma';

export type QippoPresence = 'mapped' | 'qippo-only' | 'qipper-only' | 'needs-review';
export type QippoConfidence = 'high' | 'medium' | 'needs-review';

export interface QippoComponentRef {
  id: string;
  name: string;
  nameFa: string;
  category: InventoryCategory;
  presence: QippoPresence;
  confidence: QippoConfidence;
  section: string;
  nodeId: string;
  figmaUrl: string;
  figmaPath: string;
  screenshot?: string;
  screenshots?: string[];
  variants: string[];
  sizes: string[];
  states: string[];
  summary: string;
  differences: string[];
  reviewPriority?: number;
  /** Inventory ids this maps onto. Empty when Qippo-only with no inventory row yet. */
  mappedInventoryId?: string;
}

function ref(
  partial: Omit<QippoComponentRef, 'figmaUrl' | 'figmaPath'> & { figmaPath?: string }
): QippoComponentRef {
  return {
    ...partial,
    figmaUrl: qippoFigmaUrl(partial.nodeId),
    figmaPath:
      partial.figmaPath ??
      `${QIPPO_FIGMA.fileName} / ${QIPPO_FIGMA.pageName} / ${partial.section} / ${partial.nodeId}`,
  };
}

export const QIPPO_CATALOG: QippoComponentRef[] = [
  ref({
    id: 'color',
    name: 'Color',
    nameFa: 'رنگ',
    category: 'foundation',
    presence: 'mapped',
    confidence: 'medium',
    section: 'local variables on components',
    nodeId: '2245:8769',
    variants: ['Primary', 'Neutral', 'Low Opacity'],
    sizes: [],
    states: [],
    summary:
      'Local variables, not a published palette page. Primary/Primary #3b8dd4, Primary/Dark-600 #2771b2. Qipper extracted primary remains #4179f0.',
    differences: [
      'Qippo teal/blue primary vs Qipper #4179f0',
      'No dedicated color page on Ui Kit',
    ],
    mappedInventoryId: 'color',
  }),
  ref({
    id: 'typography',
    name: 'Typography',
    nameFa: 'تایپوگرافی',
    category: 'foundation',
    presence: 'needs-review',
    confidence: 'needs-review',
    section: 'local variables on components',
    nodeId: '7130:57817',
    variants: ['Caption sm/md', 'Heading/H6', 'UI Type text-sm/xs/2xs'],
    sizes: ['10', '12', '14', '16'],
    states: [],
    summary:
      'Ui Kit mixes Yekan Bakh FaNum / VF on inputs and header with Estedad-VF on checkbox labels. Qipper live typeface is IRANYekanX. Do not pick a canonical face yet.',
    differences: [
      'Yekan Bakh vs Estedad-VF inside the same kit',
      'Qipper IRANYekanX vs Qippo Yekan Bakh / Estedad',
    ],
    mappedInventoryId: 'typography',
  }),
  ref({
    id: 'spacing',
    name: 'Spacing',
    nameFa: 'فاصله',
    category: 'foundation',
    presence: 'mapped',
    confidence: 'medium',
    section: 'Paddings/UI variables',
    nodeId: '7130:57817',
    variants: ['--padding-none/6xs/5xs/4xs'],
    sizes: ['0', '4', '8', '12'],
    states: [],
    summary: 'Observed padding tokens 0 / 4 / 8 / 12. No full spacing page. Qipper uses space-1..8 plus page-x.',
    differences: ['Qippo padding scale sampled from fields is 4-based; Qipper has a wider space scale'],
    mappedInventoryId: 'spacing',
  }),
  ref({
    id: 'radius',
    name: 'Border Radius',
    nameFa: 'شعاع گوشه',
    category: 'foundation',
    presence: 'mapped',
    confidence: 'high',
    section: 'Border radius variables',
    nodeId: '2245:8769',
    variants: ['xs 4', 'sm 8', 'md 12', 'xl 24'],
    sizes: ['4', '8', '12', '24'],
    states: [],
    summary:
      'Buttons bind --radius-xl 24 on 32/40/48 heights, so Primary reads as a pill. Qipper buttons use a less circular radius.',
    differences: ['Qippo pill (--radius-xl 24) vs Qipper rounded-xl control'],
    mappedInventoryId: 'radius',
  }),
  ref({
    id: 'elevation',
    name: 'Shadows',
    nameFa: 'سایه',
    category: 'foundation',
    presence: 'needs-review',
    confidence: 'needs-review',
    section: 'Ui Kit (no dedicated section)',
    nodeId: '1:3',
    variants: [],
    sizes: [],
    states: [],
    summary: 'No named shadow/elevation scale was selected as variables on sampled nodes. Cards show soft drop shadows visually.',
    differences: ['Qipper has shadow-light / heavy / glow tokens; Qippo scale not confirmed'],
    mappedInventoryId: 'elevation',
  }),
  ref({
    id: 'icons',
    name: 'Magicoon',
    nameFa: 'آیکون Magicoon',
    category: 'foundation',
    presence: 'mapped',
    confidence: 'high',
    section: 'Magicoon - regular / Magicoon - filled',
    nodeId: '2024:6267',
    variants: ['regular', 'filled'],
    sizes: ['24 typical'],
    states: [],
    summary:
      'Two Magicoon sets (regular + filled) plus bank logos in Other Icons. Qipper uses lucide-react. Not the same icon language.',
    differences: ['Magicoon vs lucide-react', 'Bank logos are product assets, not a generic icon set'],
    mappedInventoryId: 'icons',
  }),
  ref({
    id: 'button',
    name: 'Button',
    nameFa: 'دکمه',
    category: 'primitive',
    presence: 'mapped',
    confidence: 'high',
    section: 'Button-Component',
    nodeId: '2230:6522',
    screenshot: 'button-matrix.png',
    reviewPriority: 1,
    variants: ['Primary', 'Secondary', 'Stroke', 'Ghost', 'Text Only'],
    sizes: ['Sm 32px', 'Md 40px', 'Lg 48px'],
    states: ['Default', 'hover', 'selected', 'enable=off'],
    summary:
      'مرجع کیپو از مسیر فعال کتابخانه برداشته شد و در آرشیو ۲۰۲۶-۱۰-۱۰ مانده است. دکمهٔ مشترک خانوادهٔ Button است، نه دو پیاده‌سازی هم‌زمان.',
    differences: [
      'Qippo Stroke + Text Only; Qipper has danger and outline/soft aliases',
      'Qippo icon status is a variant; Qipper icons are children',
      'Qippo selected + hover are named states; Qipper hover is CSS-only',
      'Qippo Sm/Md/Lg = 32/40/48; Qipper sm/md/lg plus frequent className !h-12',
      'Qippo pill radius vs Qipper rounded-xl',
      'No loading state observed in Figma names',
    ],
    mappedInventoryId: 'button',
  }),
  ref({
    id: 'icon-button',
    name: 'Icon Button',
    nameFa: 'دکمه آیکونی',
    category: 'primitive',
    presence: 'qippo-only',
    confidence: 'high',
    section: 'Header-Component / icon-Button',
    nodeId: '2039:3836',
    screenshot: 'icon-button.png',
    reviewPriority: 5,
    variants: ['Badge=yes', 'Badge=No'],
    sizes: ['48', '56'],
    states: ['Default', 'Hover', 'Selected'],
    summary:
      'مرجع کیپو از مسیر فعال برداشته شد. IconButton مشترک در کتابخانه است. سابقهٔ گرهٔ فیگما حفظ شده است.',
    differences: ['Shared Icon Button primitive in Qippo; Qipper has no extracted IconButton'],
    mappedInventoryId: 'icon-button',
  }),
  ref({
    id: 'input',
    name: 'Text input',
    nameFa: 'ورودی',
    category: 'primitive',
    presence: 'mapped',
    confidence: 'high',
    section: 'Other-Component',
    nodeId: '7130:57816',
    screenshot: 'input-sm-default.png',
    screenshots: ['input-sm-default.png', 'input-error.png'],
    reviewPriority: 2,
    variants: ['Floating label yes/no', 'Fielded yes/no', 'Theme Light/Dark'],
    sizes: ['sm ~80', 'md ~96', 'lg ~104', 'xl ~74 (full field including caption)'],
    states: ['Default', 'Disable', 'Hover', 'Active', 'Eror'],
    summary:
      'LIVE React (qippo/Input.tsx). Soft filled field with optional floating label, caption, icons, Eror state. Heights include helper text.',
    differences: [
      'Qippo outlined + floating label vs Qipper borderless h-11 FieldLabel-above',
      'Qippo size scale vs Qipper single control height',
      'Qippo Light/Dark as a component axis; Qipper uses theme tokens',
      'Qippo end/start icons from Magicoon, not lucide children',
    ],
    mappedInventoryId: 'input',
  }),
  ref({
    id: 'select',
    name: 'Select',
    nameFa: 'انتخابگر',
    category: 'primitive',
    presence: 'mapped',
    confidence: 'high',
    section: 'Other-Component',
    nodeId: '7347:24406',
    screenshot: 'select-closed.png',
    screenshots: ['select-closed.png', 'select-open.png'],
    reviewPriority: 3,
    variants: ['Floating label yes/no', 'Fielded yes/no', 'Theme light/Dark', 'Open yes/no'],
    sizes: ['sm', 'md', 'lg'],
    states: ['Default', 'Open', 'Eror', 'Disable (via State)'],
    summary:
      'LIVE React (qippo/Select.tsx). Closed/open menu with checkmarks, not a searchable combobox.',
    differences: [
      'Qippo is a closed/open menu; Qipper Select is searchable by default',
      'Qippo size + floating label axes; Qipper has labeled vs unlabeled toolbar',
      'Qippo menu items show trailing check; Qipper highlights the row',
    ],
    mappedInventoryId: 'select',
  }),
  ref({
    id: 'checkbox',
    name: 'Checkbox',
    nameFa: 'چک‌باکس',
    category: 'primitive',
    presence: 'mapped',
    confidence: 'high',
    section: 'Other-Component',
    nodeId: '2896:22985',
    screenshot: 'checkbox.png',
    variants: ['simple', 'Item', 'Item+Desc', 'RTL'],
    sizes: ['control ~16–20'],
    states: ['unchecked', 'checked', 'disabled (inferred from matrix)'],
    summary:
      'LIVE React (qippo/Checkbox.tsx). Classic square with optional Item / Item+Desc rows.',
    differences: [
      'Qippo has labeled Item + description compositions; Qipper is a bare control',
      'Qipper uses button role instead of native input',
    ],
    mappedInventoryId: 'checkbox',
  }),
  ref({
    id: 'radio',
    name: 'Radio',
    nameFa: 'رادیو',
    category: 'primitive',
    presence: 'mapped',
    confidence: 'high',
    section: 'Other-Component',
    nodeId: '2858:4242',
    screenshot: 'radio.png',
    variants: ['simple', 'Item', 'Item+Desc', 'RTL'],
    sizes: [],
    states: ['unselected', 'selected'],
    summary:
      'LIVE React (qippo/Radio.tsx). Classic circular radio. Qipper RadioGroup is segmented — large API gap.',
    differences: [
      'Qippo classic radio vs Qipper segmented RadioGroup / RadioPills',
      'Qippo Item+Desc list rows; Qipper has no classic radio primitive',
    ],
    mappedInventoryId: 'radio',
  }),
  ref({
    id: 'switch',
    name: 'Switch',
    nameFa: 'سوییچ',
    category: 'primitive',
    presence: 'qippo-only',
    confidence: 'high',
    section: 'Other-Component',
    nodeId: '2014:3071',
    screenshot: 'switch.png',
    variants: ['Icon on/off', 'Custom colour'],
    sizes: ['2xs', 'xs', 'sm'],
    states: ['On', 'Off'],
    summary: 'LIVE React (qippo/Switch.tsx). iOS-style switch; Qippo-only — no Qipper twin.',
    differences: ['Absent from Qipper shared UI'],
    mappedInventoryId: 'switch',
  }),
  ref({
    id: 'slider',
    name: 'Slider / Stepper',
    nameFa: 'اسلایدر',
    category: 'primitive',
    presence: 'qippo-only',
    confidence: 'medium',
    section: 'Other-Component',
    nodeId: '2023:3412',
    variants: ['Range', 'Level', 'Stepper'],
    sizes: [],
    states: [],
    summary:
      'Range/level slider and stepper live in Other-Component. Visual inspected from page metadata; treat interaction details as Needs Review if used.',
    differences: ['Absent from Qipper shared UI'],
    mappedInventoryId: 'slider',
  }),
  ref({
    id: 'tabs',
    name: 'Tabs',
    nameFa: 'تب',
    category: 'navigation',
    presence: 'mapped',
    confidence: 'high',
    section: 'Tab',
    nodeId: '2035:4098',
    screenshot: 'tabs.png',
    screenshots: ['tabs.png', 'segmented.png'],
    reviewPriority: 4,
    variants: ['Tab-Button', 'Tab bar Count=2/3', 'Horizontal tabs Count=2/3/4'],
    sizes: [],
    states: ['Selected', 'Default', 'Hover', 'Disable'],
    summary:
      'LIVE React (qippo/Tabs.tsx underline). Segmented is separate (qippo/Segmented.tsx).',
    differences: [
      'Qippo splits Tab vs Segmented control; Qipper combines them on Tabs',
      'Qippo tab bar count is a variant; Qipper is data-driven',
    ],
    mappedInventoryId: 'tabs',
  }),
  ref({
    id: 'segmented-pills',
    name: 'Segmented control',
    nameFa: 'کنترل قطعه‌ای',
    category: 'primitive',
    presence: 'mapped',
    confidence: 'high',
    section: 'Other-Component',
    nodeId: '7506:49134',
    screenshot: 'segmented.png',
    variants: ['2–4 segments (from matrix)'],
    sizes: [],
    states: ['selected', 'default'],
    summary:
      'LIVE React (qippo/Segmented.tsx). Closer to Qipper RadioPills / SegmentedPills than classic radio.',
    differences: ['Qipper has three overlapping APIs (Tabs, RadioPills, SegmentedPills) for one Qippo control'],
    mappedInventoryId: 'segmented-pills',
  }),
  ref({
    id: 'card',
    name: 'Card',
    nameFa: 'کارت',
    category: 'data-display',
    presence: 'mapped',
    confidence: 'medium',
    section: 'Card-Component',
    nodeId: '2325:1506',
    screenshot: 'card-landing.png',
    variants: ['Landing info', 'Add Card', 'charts', 'product widgets'],
    sizes: ['~381 wide add-card', 'landing info large'],
    states: [],
    summary:
      'LIVE fair-lab surface (qippo/Card.tsx). Figma Card-Component is product modules — not screenshot dumps.',
    differences: [
      'Qipper Card is a padded surface; Qippo cards are composed product modules',
      'Add Card / upload receipt is a flow, not a primitive',
    ],
    mappedInventoryId: 'card',
  }),
  ref({
    id: 'avatar',
    name: 'Avatar',
    nameFa: 'آواتار',
    category: 'data-display',
    presence: 'mapped',
    confidence: 'high',
    section: 'Other-Component',
    nodeId: '2066:1223',
    screenshot: 'avatar.png',
    variants: ['Initials', 'Image', 'Icon', 'RTL/LTR', 'Light'],
    sizes: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    states: [],
    summary:
      'LIVE React (qippo/Avatar.tsx). Qipper PersianAvatar is widget-level and not extracted.',
    differences: ['Qippo is a kit primitive; Qipper avatar is product chrome'],
    mappedInventoryId: 'avatar',
  }),
  ref({
    id: 'toast',
    name: 'Snackbar',
    nameFa: 'اسنک‌بار',
    category: 'feedback',
    presence: 'needs-review',
    confidence: 'medium',
    section: 'Other-Component',
    nodeId: '2302:1232',
    screenshot: 'snackbar.png',
    variants: [],
    sizes: [],
    states: [],
    summary:
      'LIVE React (qippo/Snackbar.tsx). Conceptual map to Qipper InlineNotice only.',
    differences: ['Qippo snackbar vs Qipper inline notice banner'],
    mappedInventoryId: 'toast',
  }),
  ref({
    id: 'date-picker',
    name: 'Date picker',
    nameFa: 'انتخاب تاریخ',
    category: 'specialized',
    presence: 'mapped',
    confidence: 'high',
    section: 'Other-Component',
    nodeId: '7453:49460',
    screenshot: 'date-picker.png',
    variants: ['Year', 'Month', 'Day', 'Fielded', 'Theme Light/Dark', 'Direction RTL'],
    sizes: ['panel ~320×300–388'],
    states: ['Open=yes', 'closed field'],
    summary:
      'Jalali-looking RTL calendar with year/month/day drill-down. Separate date-time component exists (3296:54884). Qipper DatePicker uses persian-date-kit.',
    differences: [
      'Both are Jalali/RTL — confirm numeral/typeface later',
      'Qippo has explicit Year/Month/Day states; Qipper is a single popover calendar',
    ],
    mappedInventoryId: 'date-picker',
  }),
  ref({
    id: 'app-chrome',
    name: 'Header',
    nameFa: 'هدر',
    category: 'layout',
    presence: 'mapped',
    confidence: 'high',
    section: 'Header-Component',
    nodeId: '2287:6171',
    screenshot: 'header.png',
    variants: ['Light mode', 'Dark mode'],
    sizes: ['1344×64'],
    states: [],
    summary:
      'App header 64px with logo, icon-buttons, notification, settings, profile. Qipper header lives in widgets and was not extracted.',
    differences: ['Both are product chrome; neither is a rahino-ui primitive yet'],
    mappedInventoryId: 'app-chrome',
  }),
  ref({
    id: 'qippo-logo',
    name: 'Qippo Logo',
    nameFa: 'لوگوی کیپو',
    category: 'specialized',
    presence: 'qippo-only',
    confidence: 'high',
    section: 'Header-Component',
    nodeId: '2009:10413',
    screenshot: 'logo.png',
    variants: [],
    sizes: ['137×55'],
    states: [],
    summary: 'Product wordmark. Keep product-specific, same rule as Qipper Logo (not extracted).',
    differences: ['Different product marks; do not merge into one Rahino logo'],
  }),
  ref({
    id: 'otp',
    name: 'Login Code',
    nameFa: 'کد ورود',
    category: 'primitive',
    presence: 'qippo-only',
    confidence: 'medium',
    section: 'Tab / Login Code',
    nodeId: '2187:3585',
    screenshot: 'otp.png',
    variants: [],
    sizes: ['single cell stack'],
    states: ['multiple visual states in the stack'],
    summary: 'LIVE React (qippo/Otp.tsx). Qippo-only login-code cells.',
    differences: ['Qippo-only'],
  }),
  ref({
    id: 'auth-shell',
    name: 'Login',
    nameFa: 'ورود',
    category: 'specialized',
    presence: 'mapped',
    confidence: 'medium',
    section: 'Login',
    nodeId: '2761:19756',
    screenshot: 'login-light.png',
    variants: ['Form', 'Error', 'Success', 'Sign-up', 'Dark Default/correct/Error/Sign-up'],
    sizes: ['full screens'],
    states: ['Form', 'Error', 'Success'],
    summary:
      'Full login/sign-up screens (light + dark), not a reusable AuthShell primitive. Qipper AuthShell is a glass layout with injected mark.',
    differences: ['Qippo is a screen kit; Qipper is a layout shell'],
    mappedInventoryId: 'auth-shell',
  }),
  ref({
    id: 'file-upload',
    name: 'Add Card / upload',
    nameFa: 'آپلود رسید',
    category: 'specialized',
    presence: 'qippo-only',
    confidence: 'medium',
    section: 'Not Categorised / Add Card',
    nodeId: '2439:3941',
    variants: ['empty', 'file named', 'error'],
    sizes: ['381 wide'],
    states: ['Vacant Image Error'],
    summary:
      'Add-transaction card with receipt upload. Product flow. Inventory file-upload is missing on Qipper side.',
    differences: ['Qippo has a designed upload card; Qipper has no shared FileUpload'],
    mappedInventoryId: 'file-upload',
  }),
  ref({
    id: 'metric-card',
    name: 'Module cards',
    nameFa: 'کارت ماژول',
    category: 'data-display',
    presence: 'needs-review',
    confidence: 'needs-review',
    section: 'Module Components',
    nodeId: '3189:47970',
    screenshot: 'module-cards.png',
    variants: [
      'Currency',
      'Debt/credit',
      'Calculator',
      'Financial Report',
      'Exchange Rate',
      'Timeline',
      'Income',
      'Outcome',
    ],
    sizes: [],
    states: ['Light set sampled'],
    summary:
      'Finance module widgets, not Qipper MetricCard layouts (hero/radar/stat/progress). Mapping is thematic only — Needs Review.',
    differences: [
      'Qippo product modules vs Qipper KPI MetricCard API',
      'Do not treat Currency/Debt cards as MetricCard variants',
    ],
    mappedInventoryId: 'metric-card',
  }),
  ref({
    id: 'dialog',
    name: 'Dialog / Modal',
    nameFa: 'مودال',
    category: 'overlay',
    presence: 'qipper-only',
    confidence: 'needs-review',
    section: 'Ui Kit (no named Modal/Dialog)',
    nodeId: '1:3',
    variants: [],
    sizes: [],
    states: [],
    summary:
      'No component named Modal, Dialog, or Drawer on the Ui Kit page. Overlays may be buried in Prototyping / Not Categorised — do not invent a Qippo modal.',
    differences: ['Qipper Modal is extracted; Qippo has no named equivalent on this page'],
    mappedInventoryId: 'dialog',
  }),
  ref({
    id: 'data-table',
    name: 'Table',
    nameFa: 'جدول',
    category: 'data-display',
    presence: 'qipper-only',
    confidence: 'needs-review',
    section: 'Ui Kit (no named Table)',
    nodeId: '1:3',
    variants: [],
    sizes: [],
    states: [],
    summary:
      'No named Table / Data table / Pagination primitive on Ui Kit. Qipper Table + DataTable stay Qipper-only until a Qippo table is found on product pages (out of this pass).',
    differences: ['Qipper-only on this page'],
    mappedInventoryId: 'data-table',
  }),
  ref({
    id: 'badge',
    name: 'Badge',
    nameFa: 'نشان',
    category: 'feedback',
    presence: 'qipper-only',
    confidence: 'needs-review',
    section: 'Magicoon (icon overlay named Badge)',
    nodeId: '2024:6388',
    variants: [],
    sizes: ['32×14 overlay on icons'],
    states: [],
    summary:
      'Frames named Badge on Magicoon icons are notification dots/overlays, not Qipper status Badge (success/warning/error). No status-badge set found.',
    differences: ['Different meaning of “Badge”'],
    mappedInventoryId: 'badge',
  }),
  ref({
    id: 'notification',
    name: 'Notification panel',
    nameFa: 'اعلان',
    category: 'feedback',
    presence: 'mapped',
    confidence: 'medium',
    section: 'Header-Component',
    nodeId: '2041:4264',
    variants: ['Notification', 'No results'],
    sizes: ['~298×351–414'],
    states: ['empty', 'list'],
    summary: 'Header notification popover. Qipper NotificationDrawer is widget-level, not extracted.',
    differences: ['Both product chrome'],
    mappedInventoryId: 'notification',
  }),
  ref({
    id: 'dropdown-menu',
    name: 'Profile / Settings',
    nameFa: 'منوی پروفایل',
    category: 'overlay',
    presence: 'mapped',
    confidence: 'medium',
    section: 'Header-Component',
    nodeId: '2009:10331',
    variants: ['Profile', 'Settings'],
    sizes: ['~320 wide'],
    states: [],
    summary: 'Profile and Settings panels in the header kit. Qipper HeaderProfileDropdown is widget-level.',
    differences: ['Both product chrome'],
    mappedInventoryId: 'dropdown-menu',
  }),
  ref({
    id: 'bank-logos',
    name: 'Bank logos',
    nameFa: 'لوگوی بانک',
    category: 'specialized',
    presence: 'qippo-only',
    confidence: 'high',
    section: 'Other Icons',
    nodeId: '2024:15446',
    variants: ['Keshavarzi', 'Mellat', 'others in the set'],
    sizes: [],
    states: [],
    summary: 'Iranian bank marks. Product assets, not a Rahino primitive.',
    differences: ['Qippo-only product assets'],
  }),
];

export function getQippoComponent(id: string) {
  return QIPPO_CATALOG.find((item) => item.id === id);
}

export function qippoByPresence(presence: QippoPresence) {
  return QIPPO_CATALOG.filter((item) => item.presence === presence);
}

export const QIPPO_REVIEW_FIRST = QIPPO_CATALOG.filter(
  (item) => item.reviewPriority != null
).sort((a, b) => (a.reviewPriority ?? 99) - (b.reviewPriority ?? 99));

export function qippoOnlyInventoryItems(): InventoryItem[] {
  return QIPPO_CATALOG.filter((item) => item.presence === 'qippo-only' && !item.mappedInventoryId).map(
    (item) => ({
      id: item.id,
      name: item.name,
      category: item.category,
      status: 'needs-review' as const,
      presence: item.presence,
      qippoSource: item.figmaPath,
      notes: item.summary,
      variants: item.variants,
      states: item.states,
      productSpecific: item.id === 'qippo-logo' || item.id === 'bank-logos',
    })
  );
}
