export type InventoryStatus =
  | 'extracted'
  | 'existing'
  | 'missing'
  | 'needs-review'
  | 'proposed'
  | 'approved'
  | 'deprecated';

export type InventoryCategory =
  | 'foundation'
  | 'primitive'
  | 'feedback'
  | 'overlay'
  | 'navigation'
  | 'data-display'
  | 'layout'
  | 'specialized'
  | 'utility';

export interface InventoryItem {
  id: string;
  name: string;
  category: InventoryCategory;
  status: InventoryStatus;
  qipperSource?: string;
  extractedPath?: string;
  variants?: string[];
  states?: string[];
  dependencies?: string[];
  productSpecific?: boolean;
  knownIssues?: string[];
  designDecisionsNeeded?: string[];
  notes?: string;
}

export const INVENTORY: InventoryItem[] = [
  // Foundations
  {
    id: 'color',
    name: 'Color',
    category: 'foundation',
    status: 'extracted',
    qipperSource: 'src/app/styles/tokens.css',
    extractedPath: 'src/styles/tokens.css',
    notes: 'Qipper --qipper-* tokens copied. --rahino-* aliases track the same values.',
    designDecisionsNeeded: ['Canonical brand palette vs Qippo Figma', 'Product theme slots'],
  },
  {
    id: 'typography',
    name: 'Typography',
    category: 'foundation',
    status: 'extracted',
    qipperSource: 'src/app/styles/index.css',
    extractedPath: 'src/styles/index.css',
    notes: 'Live typeface is IRANYekanX (copied from Qipper public/fonts). Qipper tokens.css still lists Vazirmatn in --qipper-font-sans; @theme uses IRANYekanX.',
    designDecisionsNeeded: ['Typeface (IRANYekanX vs Vazirmatn vs Qippo)'],
  },
  {
    id: 'spacing',
    name: 'Spacing',
    category: 'foundation',
    status: 'extracted',
    qipperSource: 'src/app/styles/tokens.css',
    extractedPath: 'src/styles/tokens.css',
    variants: ['space-1..8', 'page-x'],
  },
  {
    id: 'sizing',
    name: 'Sizing',
    category: 'foundation',
    status: 'extracted',
    notes: 'Control height h-11 is the Qipper field canon (FIELD.control).',
    qipperSource: 'src/shared/ui/fieldTokens.ts',
    extractedPath: 'src/tokens/fieldTokens.ts',
  },
  {
    id: 'radius',
    name: 'Border Radius',
    category: 'foundation',
    status: 'extracted',
    qipperSource: 'src/app/styles/tokens.css',
    extractedPath: 'src/styles/tokens.css',
    knownIssues: ['tokens.css radius scale differs from index.css --radius-sm/md/lg pixel values'],
    designDecisionsNeeded: ['Single radius scale'],
  },
  {
    id: 'borders',
    name: 'Borders',
    category: 'foundation',
    status: 'extracted',
    qipperSource: 'src/app/styles/tokens.css',
    extractedPath: 'src/styles/tokens.css',
  },
  {
    id: 'elevation',
    name: 'Shadows / Elevation',
    category: 'foundation',
    status: 'extracted',
    qipperSource: 'src/app/styles/tokens.css',
    extractedPath: 'src/styles/tokens.css',
    variants: ['shadow-light', 'shadow-heavy', 'shadow-glow'],
  },
  {
    id: 'motion',
    name: 'Motion',
    category: 'foundation',
    status: 'existing',
    notes: 'Framer Motion springs live inside Button/Modal/Tabs. No shared motion tokens yet.',
    designDecisionsNeeded: ['Shared duration/easing tokens'],
  },
  {
    id: 'icons',
    name: 'Icons',
    category: 'foundation',
    status: 'existing',
    notes: 'lucide-react is used throughout Qipper. Not packaged as a Rahino icon set.',
    designDecisionsNeeded: ['Icon library vs custom set'],
  },
  {
    id: 'breakpoints',
    name: 'Breakpoints',
    category: 'foundation',
    status: 'extracted',
    qipperSource: 'src/app/styles/index.css',
    extractedPath: 'src/styles/index.css',
  },
  {
    id: 'z-index',
    name: 'Z-index',
    category: 'foundation',
    status: 'missing',
    notes: 'Hardcoded z-[100], z-[220], z-[80] in overlays. No token scale.',
  },
  {
    id: 'accessibility',
    name: 'Accessibility',
    category: 'foundation',
    status: 'needs-review',
    notes: 'Some roles/labels exist; focus rings are ad hoc. Needs a11y pass vs Qippo.',
  },
  {
    id: 'rtl',
    name: 'RTL / Direction',
    category: 'foundation',
    status: 'extracted',
    notes: 'Default RTL. Input supports dir=ltr for credentials. Physical left/right still used in several fields.',
    knownIssues: ['Select chevron uses left-0 rather than logical start/end'],
  },

  // Primitives — extracted
  {
    id: 'button',
    name: 'Button',
    category: 'primitive',
    status: 'needs-review',
    qipperSource: 'src/shared/ui/Button.tsx',
    extractedPath: 'src/components/Button.tsx',
    variants: ['primary', 'secondary', 'ghost', 'danger', 'outline→secondary', 'soft→secondary'],
    states: ['default', 'hover', 'active', 'disabled', 'loading', 'focus-visible'],
    dependencies: ['framer-motion', 'clsx', 'tailwind-merge'],
    designDecisionsNeeded: ['Variant set vs Qippo', 'Icon button as separate component?'],
  },
  {
    id: 'icon-button',
    name: 'Icon Button',
    category: 'primitive',
    status: 'missing',
    notes: 'Close/back buttons are inline, not a shared component.',
  },
  {
    id: 'link',
    name: 'Link',
    category: 'primitive',
    status: 'missing',
  },
  {
    id: 'text',
    name: 'Text',
    category: 'primitive',
    status: 'missing',
  },
  {
    id: 'heading',
    name: 'Heading',
    category: 'primitive',
    status: 'missing',
  },
  {
    id: 'label',
    name: 'Label',
    category: 'primitive',
    status: 'extracted',
    qipperSource: 'src/shared/ui/FormField.tsx',
    extractedPath: 'src/components/FormField.tsx',
    notes: 'FieldLabel is part of FormField, not a standalone typography primitive.',
  },
  {
    id: 'input',
    name: 'Input',
    category: 'primitive',
    status: 'needs-review',
    qipperSource: 'src/shared/ui/Input.tsx',
    extractedPath: 'src/components/Input.tsx',
    variants: ['default', 'mono', 'dense', 'ltr'],
    states: ['default', 'hover', 'focus', 'error', 'disabled'],
    dependencies: ['FormField', 'FIELD tokens'],
  },
  {
    id: 'textarea',
    name: 'Textarea',
    category: 'primitive',
    status: 'extracted',
    qipperSource: 'src/shared/ui/Textarea.tsx',
    extractedPath: 'src/components/Textarea.tsx',
    states: ['default', 'focus', 'error', 'disabled'],
  },
  {
    id: 'input-group',
    name: 'Input Group',
    category: 'primitive',
    status: 'existing',
    notes: 'Input has icon + endAdornment, not a general InputGroup primitive.',
    qipperSource: 'src/shared/ui/Input.tsx',
  },
  {
    id: 'field',
    name: 'Field',
    category: 'primitive',
    status: 'extracted',
    qipperSource: 'src/shared/ui/FormField.tsx',
    extractedPath: 'src/components/FormField.tsx',
    variants: ['default', 'dense', 'hideLabel'],
    dependencies: ['FIELD tokens'],
  },
  {
    id: 'checkbox',
    name: 'Checkbox',
    category: 'primitive',
    status: 'extracted',
    qipperSource: 'src/shared/ui/Checkbox.tsx',
    extractedPath: 'src/components/Checkbox.tsx',
    states: ['unchecked', 'checked', 'disabled', 'focus'],
    knownIssues: ['No indeterminate state', 'Button role instead of native input'],
  },
  {
    id: 'radio',
    name: 'Radio',
    category: 'primitive',
    status: 'extracted',
    qipperSource: 'src/shared/ui/RadioGroup.tsx',
    extractedPath: 'src/components/RadioGroup.tsx',
    variants: ['RadioGroup (segmented)', 'RadioPills'],
    notes: 'Segmented control, not a classic radio circle.',
    designDecisionsNeeded: ['Keep as segmented control vs add classic radio'],
  },
  {
    id: 'switch',
    name: 'Switch',
    category: 'primitive',
    status: 'missing',
  },
  {
    id: 'slider',
    name: 'Slider',
    category: 'primitive',
    status: 'missing',
  },
  {
    id: 'select',
    name: 'Select',
    category: 'primitive',
    status: 'needs-review',
    qipperSource: 'src/shared/ui/Select.tsx',
    extractedPath: 'src/components/Select.tsx',
    variants: ['searchable', 'static'],
    states: ['closed', 'open', 'selected', 'empty', 'error', 'disabled'],
    productSpecific: false,
    knownIssues: ['Persian placeholder/empty copy hardcoded', 'Click-outside only, limited keyboard nav'],
  },
  {
    id: 'combobox',
    name: 'Combobox',
    category: 'primitive',
    status: 'existing',
    notes: 'Searchable Select covers part of this; not a WAI-ARIA combobox.',
  },
  {
    id: 'autocomplete',
    name: 'Autocomplete',
    category: 'primitive',
    status: 'missing',
  },

  // Feedback
  {
    id: 'alert',
    name: 'Alert',
    category: 'feedback',
    status: 'missing',
  },
  {
    id: 'toast',
    name: 'Toast',
    category: 'feedback',
    status: 'extracted',
    qipperSource: 'src/features/tasks/components/duties/DutyNotice.tsx',
    extractedPath: 'src/components/InlineNotice.tsx',
    notes: 'Renamed from DutyNotice. Single-message banner, not a toast queue.',
  },
  {
    id: 'notification',
    name: 'Notification',
    category: 'feedback',
    status: 'existing',
    qipperSource: 'src/widgets/layout/header/NotificationDrawer.tsx',
    notes: 'Lives in widgets (out of Phase 1 extract scope).',
  },
  {
    id: 'progress',
    name: 'Progress',
    category: 'feedback',
    status: 'existing',
    notes: 'MetricCard layout=progress is a KPI bar, not a general Progress primitive.',
  },
  {
    id: 'spinner',
    name: 'Spinner',
    category: 'feedback',
    status: 'existing',
    notes: 'Inline SVG in Button loading + lucide Loader2 in DataLoadingState.',
  },
  {
    id: 'skeleton',
    name: 'Skeleton',
    category: 'feedback',
    status: 'missing',
  },
  {
    id: 'badge',
    name: 'Badge',
    category: 'feedback',
    status: 'needs-review',
    qipperSource: 'src/shared/ui/Badge.tsx',
    extractedPath: 'src/components/Badge.tsx',
    variants: ['emerald/success', 'blue/primary', 'rose/error/danger', 'amber/warning', 'purple→primary', 'slate', 'outline'],
    states: ['sm', 'md', 'lg'],
  },
  {
    id: 'status-indicator',
    name: 'Status Indicator',
    category: 'feedback',
    status: 'existing',
    qipperSource: 'src/features/tasks/components/task-details/StatusBadge.tsx',
    productSpecific: true,
    notes: 'Hardcoded TaskStatus enum. Do not extract until a tokenized status map exists.',
  },

  // Overlays
  {
    id: 'dialog',
    name: 'Dialog / Modal',
    category: 'overlay',
    status: 'needs-review',
    qipperSource: 'src/shared/ui/Modal.tsx',
    extractedPath: 'src/components/Modal.tsx',
    variants: ['sm', 'md', 'lg', 'xl', '2xl', 'ModalFormCard', 'ChoiceTile'],
    states: ['open', 'closed', 'esc', 'backdrop'],
    knownIssues: ['Close label is Persian-only', 'ChoiceTile originated as finance tile'],
  },
  {
    id: 'drawer',
    name: 'Drawer',
    category: 'overlay',
    status: 'existing',
    qipperSource: 'src/widgets/layout/header/NotificationDrawer.tsx',
    notes: 'Widget-level; not extracted.',
  },
  {
    id: 'popover',
    name: 'Popover',
    category: 'overlay',
    status: 'existing',
    notes: 'Ad hoc popovers in Select, TimePicker, DataTable column menu.',
  },
  {
    id: 'tooltip',
    name: 'Tooltip',
    category: 'overlay',
    status: 'existing',
    qipperSource: 'src/widgets/layout/sidebar/SidebarTooltip.tsx',
    notes: 'Widget-level.',
  },
  {
    id: 'dropdown-menu',
    name: 'Dropdown Menu',
    category: 'overlay',
    status: 'existing',
    qipperSource: 'src/widgets/layout/header/HeaderProfileDropdown.tsx',
    notes: 'Product chrome, not extracted.',
  },
  {
    id: 'context-menu',
    name: 'Context Menu',
    category: 'overlay',
    status: 'missing',
  },
  {
    id: 'command-menu',
    name: 'Command Menu',
    category: 'overlay',
    status: 'existing',
    qipperSource: 'src/widgets/layout/header/CommandPalette.tsx',
    notes: 'Widget-level command palette. Out of Phase 1 extract scope.',
  },

  // Navigation
  {
    id: 'tabs',
    name: 'Tabs',
    category: 'navigation',
    status: 'extracted',
    qipperSource: 'src/shared/ui/Tabs.tsx',
    extractedPath: 'src/components/Tabs.tsx',
    variants: ['segmented', 'underline', 'sm/md/lg'],
    states: ['active', 'disabled', 'badge'],
  },
  {
    id: 'breadcrumb',
    name: 'Breadcrumb',
    category: 'navigation',
    status: 'missing',
  },
  {
    id: 'pagination',
    name: 'Pagination',
    category: 'navigation',
    status: 'extracted',
    qipperSource: 'src/shared/ui/QipperTable/QipperTablePagination.tsx',
    extractedPath: 'src/components/DataTable/DataTablePagination.tsx',
    notes: 'Currently coupled to DataTable. Could be promoted later.',
  },
  {
    id: 'navigation-menu',
    name: 'Navigation Menu',
    category: 'navigation',
    status: 'existing',
    qipperSource: 'src/widgets/layout/Sidebar.tsx',
    notes: 'App chrome. Out of Phase 1 extract scope.',
  },
  {
    id: 'stepper',
    name: 'Stepper',
    category: 'navigation',
    status: 'existing',
    qipperSource: 'src/features/finance/components/create-ledger/CreateLedgerStepIndicator.tsx',
    productSpecific: true,
    notes: 'Fixed 4-step finance wizard. Do not extract.',
  },

  // Data display
  {
    id: 'card',
    name: 'Card',
    category: 'data-display',
    status: 'extracted',
    qipperSource: 'src/shared/ui/Card.tsx',
    extractedPath: 'src/components/Card.tsx',
    variants: ['padding on/off'],
  },
  {
    id: 'avatar',
    name: 'Avatar',
    category: 'data-display',
    status: 'existing',
    qipperSource: 'src/widgets/dashboard/components/PersianAvatar.tsx',
    notes: 'Widget-level.',
  },
  {
    id: 'avatar-group',
    name: 'Avatar Group',
    category: 'data-display',
    status: 'missing',
  },
  {
    id: 'table',
    name: 'Table',
    category: 'data-display',
    status: 'extracted',
    qipperSource: 'src/shared/ui/Table.tsx',
    extractedPath: 'src/components/Table.tsx',
    variants: ['soft', 'card', 'classic'],
    states: ['empty', 'selected', 'row-click'],
  },
  {
    id: 'data-table',
    name: 'Data Table',
    category: 'data-display',
    status: 'needs-review',
    qipperSource: 'src/shared/ui/QipperTable/',
    extractedPath: 'src/components/DataTable/',
    variants: ['card', 'compact', 'asset'],
    states: ['loading', 'empty', 'sort', 'filter', 'pagination', 'selection', 'mobile card'],
    knownIssues: [
      'Mobile role heuristics hardcode Qipper column ids (name, part, statusIcon)',
      'Persian copy in column menu/pagination',
    ],
    designDecisionsNeeded: ['One table primitive vs Table + DataTable', 'Rename away from QipperTable'],
  },
  {
    id: 'list',
    name: 'List',
    category: 'data-display',
    status: 'missing',
  },
  {
    id: 'list-item',
    name: 'List Item',
    category: 'data-display',
    status: 'extracted',
    qipperSource: 'src/features/inventory/components/product-details/InfoRow.tsx',
    extractedPath: 'src/components/DefinitionRow.tsx',
    variants: ['DefinitionRow', 'SpecRow'],
  },
  {
    id: 'accordion',
    name: 'Accordion',
    category: 'data-display',
    status: 'existing',
    qipperSource: 'src/features/logistics/components/TimelineNode.tsx',
    productSpecific: true,
  },
  {
    id: 'separator',
    name: 'Separator',
    category: 'data-display',
    status: 'missing',
  },
  {
    id: 'metric-card',
    name: 'Metric Card',
    category: 'data-display',
    status: 'extracted',
    qipperSource: 'src/shared/ui/MetricCard/',
    extractedPath: 'src/components/MetricCard/',
    variants: ['hero', 'radar', 'stat', 'inline', 'mini', 'bare', 'split', 'progress'],
    states: ['loading', 'alert', 'expanded', 'trend'],
  },
  {
    id: 'stat-card',
    name: 'Stat Card',
    category: 'data-display',
    status: 'deprecated',
    qipperSource: 'src/shared/ui/StatCard.tsx',
    extractedPath: 'src/components/StatCard.tsx',
    notes: 'Alias of MetricCard. Keep for compatibility; prefer MetricCard.',
  },

  // Layout
  {
    id: 'container',
    name: 'Container',
    category: 'layout',
    status: 'existing',
    notes: '.container-xl utility in Qipper CSS; not a React primitive.',
  },
  {
    id: 'stack',
    name: 'Stack',
    category: 'layout',
    status: 'missing',
  },
  {
    id: 'flex',
    name: 'Flex',
    category: 'layout',
    status: 'missing',
  },
  {
    id: 'grid',
    name: 'Grid',
    category: 'layout',
    status: 'extracted',
    qipperSource: 'src/shared/ui/MetricCard/MetricCardGrid.tsx',
    extractedPath: 'src/components/MetricCard/MetricCardGrid.tsx',
    notes: 'Metric-specific grid presets, not a general Grid primitive.',
  },
  {
    id: 'section',
    name: 'Section',
    category: 'layout',
    status: 'extracted',
    qipperSource: 'src/shared/ui/SectionHeader.tsx',
    extractedPath: 'src/components/SectionHeader.tsx',
  },
  {
    id: 'divider',
    name: 'Divider',
    category: 'layout',
    status: 'missing',
  },
  {
    id: 'page-shell',
    name: 'Page Shell',
    category: 'layout',
    status: 'extracted',
    qipperSource: 'src/shared/ui/PageShell.tsx',
    extractedPath: 'src/components/PageShell.tsx',
    variants: ['hub', 'viewport', 'SurfacePanel sm/md/lg'],
  },
  {
    id: 'page-header',
    name: 'Page Header',
    category: 'layout',
    status: 'extracted',
    qipperSource: 'src/shared/ui/PageHeader.tsx',
    extractedPath: 'src/components/PageHeader.tsx',
    notes: 'TanStack Router removed; back uses onBack or history.back().',
  },

  // Specialized
  {
    id: 'date-picker',
    name: 'Date Picker',
    category: 'specialized',
    status: 'needs-review',
    qipperSource: 'src/shared/ui/DatePicker.tsx',
    extractedPath: 'src/components/DatePicker.tsx',
    dependencies: ['persian-date-kit', 'ThemeProvider'],
    designDecisionsNeeded: ['Jalali as default for all Rahino products?'],
  },
  {
    id: 'calendar',
    name: 'Calendar',
    category: 'specialized',
    status: 'existing',
    notes: 'Comes from persian-date-kit inside DatePicker.',
  },
  {
    id: 'date-range-picker',
    name: 'Date Range Picker',
    category: 'specialized',
    status: 'missing',
  },
  {
    id: 'time-picker',
    name: 'Time Picker',
    category: 'specialized',
    status: 'extracted',
    qipperSource: 'src/shared/ui/TimePicker.tsx',
    extractedPath: 'src/components/TimePicker.tsx',
    variants: ['15-minute steps'],
  },
  {
    id: 'file-upload',
    name: 'File Upload',
    category: 'specialized',
    status: 'missing',
  },
  {
    id: 'search',
    name: 'Search',
    category: 'specialized',
    status: 'existing',
    notes: 'Hub pages compose Input; no Search primitive.',
  },
  {
    id: 'empty-state',
    name: 'Empty State',
    category: 'specialized',
    status: 'extracted',
    qipperSource: 'src/shared/ui/DataState.tsx',
    extractedPath: 'src/components/DataState.tsx',
    variants: ['empty', 'error', 'loading', 'compact'],
  },
  {
    id: 'error-state',
    name: 'Error State',
    category: 'specialized',
    status: 'extracted',
    qipperSource: 'src/shared/ui/DataState.tsx + ErrorBoundary.tsx',
    extractedPath: 'src/components/DataState.tsx, src/components/ErrorBoundary.tsx',
  },
  {
    id: 'confirmation',
    name: 'Confirmation',
    category: 'specialized',
    status: 'extracted',
    qipperSource: 'src/shared/ui/ConfirmationModal.tsx',
    extractedPath: 'src/components/ConfirmationModal.tsx',
    variants: ['danger', 'warning', 'info'],
    states: ['open', 'loading'],
  },
  {
    id: 'loading-state',
    name: 'Loading State',
    category: 'specialized',
    status: 'extracted',
    qipperSource: 'src/shared/ui/DataState.tsx',
    extractedPath: 'src/components/DataState.tsx',
  },
  {
    id: 'auth-shell',
    name: 'Auth Shell',
    category: 'specialized',
    status: 'extracted',
    qipperSource: 'src/pages/auth/AuthGlassShell.tsx',
    extractedPath: 'src/components/AuthShell.tsx',
    notes: 'QipperLogo removed; mark is injected.',
  },
  {
    id: 'segmented-pills',
    name: 'Segmented Pills',
    category: 'primitive',
    status: 'extracted',
    qipperSource: 'src/features/logistics/components/operation-form/SegmentedPills.tsx',
    extractedPath: 'src/components/SegmentedPills.tsx',
    notes: 'Thin RadioPills wrapper with accent tones.',
  },
  {
    id: 'appearance-controls',
    name: 'Appearance Controls',
    category: 'specialized',
    status: 'extracted',
    qipperSource: 'src/shared/ui/AppearanceControls.tsx',
    extractedPath: 'src/components/AppearanceControls.tsx',
    notes: 'Uses ThemeProvider instead of Qipper zustand store.',
  },

  // Explicitly NOT in shared DS (Qipper product)
  {
    id: 'qipper-logo',
    name: 'Qipper Logo',
    category: 'specialized',
    status: 'existing',
    qipperSource: 'src/shared/ui/QipperLogo.tsx',
    productSpecific: true,
    notes: 'Product wordmark. Not extracted into rahino-ui.',
  },
  {
    id: 'eldora-devices',
    name: 'Device frames (Eldora UI)',
    category: 'specialized',
    status: 'existing',
    qipperSource: 'src/shared/ui/eldoraui/',
    productSpecific: true,
    notes: 'Login marketing mockups. Not a DS primitive.',
  },
  {
    id: 'app-chrome',
    name: 'App chrome (Sidebar, Header, Mobile nav)',
    category: 'layout',
    status: 'existing',
    qipperSource: 'src/widgets/layout/',
    productSpecific: true,
    notes: 'Out of Phase 1 source folders. Documented for later reconciliation.',
  },
];

export const NOT_FOR_SHARED_SYSTEM = INVENTORY.filter((item) => item.productSpecific);

export function inventoryByCategory(category: InventoryCategory) {
  return INVENTORY.filter((item) => item.category === category);
}

export function inventoryByStatus(status: InventoryStatus) {
  return INVENTORY.filter((item) => item.status === status);
}
